from FiniteAutomaton.automatonTools import MealyAutomaton as me
from FiniteAutomaton.automatonTools import MooreAutomaton as mo
from automatonTools import EquivalentAutomaton as ea


if __name__ == '__main__':
    #Mealy
    print("Mealy")
    automaton = me.MealyAutomaton(["A", "B", "C", "D", "E", "F", "G", "H", "J"], [0, 1], [0, 1])
    automaton.addStateToMachine("A")
    automaton.addStateToMachine("B")
    automaton.addStateToMachine("C")
    automaton.addStateToMachine("D")
    automaton.addStateToMachine("E")
    automaton.addStateToMachine("F")
    automaton.addStateToMachine("G")
    automaton.addStateToMachine("H")
    automaton.addStateToMachine("J")

    # Formato de la función: estado, estimulo, respuesta: formato [EstadoAlQuellega, respuesta]
    automaton.addStimulusAndResponseToState("A", 0, ["B", 0])
    automaton.addStimulusAndResponseToState("A", 1, ["C", 0])
    automaton.addStimulusAndResponseToState("B", 0, ["C", 1])
    automaton.addStimulusAndResponseToState("B", 1, ["D", 1])
    automaton.addStimulusAndResponseToState("C", 0, ["D", 0])
    automaton.addStimulusAndResponseToState("C", 1, ["E", 0])
    automaton.addStimulusAndResponseToState("D", 0, ["C", 1])
    automaton.addStimulusAndResponseToState("D", 1, ["B", 1])
    automaton.addStimulusAndResponseToState("E", 0, ["F", 1])
    automaton.addStimulusAndResponseToState("E", 1, ["E", 1])
    automaton.addStimulusAndResponseToState("F", 0, ["G", 0])
    automaton.addStimulusAndResponseToState("F", 1, ["C", 0])
    automaton.addStimulusAndResponseToState("G", 0, ["F", 1])
    automaton.addStimulusAndResponseToState("G", 1, ["G", 1])
    automaton.addStimulusAndResponseToState("H", 0, ["J", 1])
    automaton.addStimulusAndResponseToState("H", 1, ["B", 0])
    automaton.addStimulusAndResponseToState("J", 0, ["H", 1])
    automaton.addStimulusAndResponseToState("J", 1, ["D", 0])
    #automaton.getEquivalentConnectAutomaton()


    #Moore
    print("Moore")
    automaton = mo.MooreAutomaton(["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K"], [0, 1], [0, 1])
    automaton.addStateToMachine("A")
    automaton.addStateToMachine("B")
    automaton.addStateToMachine("C")
    automaton.addStateToMachine("D")
    automaton.addStateToMachine("E")
    automaton.addStateToMachine("F")
    automaton.addStateToMachine("G")
    automaton.addStateToMachine("H")
    automaton.addStateToMachine("I")
    automaton.addStateToMachine("J")
    automaton.addStateToMachine("K")
    automaton.addStimulusAndResponseToState("A", {0: "B"}, 0)
    automaton.addStimulusAndResponseToState("A", {1: "A"}, 0)
    automaton.addStimulusAndResponseToState("B", {0: "C"}, 0)
    automaton.addStimulusAndResponseToState("B", {1: "D"}, 0)
    automaton.addStimulusAndResponseToState("C", {0: "E"}, 0)
    automaton.addStimulusAndResponseToState("C", {1: "C"}, 0)
    automaton.addStimulusAndResponseToState("D", {0: "F"}, 0)
    automaton.addStimulusAndResponseToState("D", {1: "B"}, 0)
    automaton.addStimulusAndResponseToState("E", {0: "G"}, 0)
    automaton.addStimulusAndResponseToState("E", {1: "E"}, 0)
    automaton.addStimulusAndResponseToState("F", {0: "H"}, 0)
    automaton.addStimulusAndResponseToState("F", {1: "F"}, 0)
    automaton.addStimulusAndResponseToState("G", {0: "I"}, 0)
    automaton.addStimulusAndResponseToState("G", {1: "G"}, 0)
    automaton.addStimulusAndResponseToState("H", {0: "J"}, 0)
    automaton.addStimulusAndResponseToState("H", {1: "H"}, 0)
    automaton.addStimulusAndResponseToState("I", {0: "A"}, 1)
    automaton.addStimulusAndResponseToState("I", {1: "K"}, 1)
    automaton.addStimulusAndResponseToState("J", {0: "K"}, 0)
    automaton.addStimulusAndResponseToState("J", {1: "J"}, 0)
    automaton.addStimulusAndResponseToState("K", {0: "A"}, 1)
    automaton.addStimulusAndResponseToState("K", {1: "K"}, 1)

